# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cbbb4bb7489a024b19253b48d960a537b580aac8ada632446ef0a24a4dd2a0d1f13123fa757aeaab77f46e90cdff1037516f20dd340d4cfa92094e4cc76530e

test:
  secret_key_base: cfa7c589cfeda0654adcdc3dadd52904c66d74e4d788a687ad709e5d999fb8a69f8ac3a0a61cc5a0f0b946bfe13676b93dc5570075cb09ae9d7c8b5bf04c8177

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
